#!/bin/sh

### Example : $ multi-scp $PATH_TO_THE_LOCAL_DIRECTORY $SSH_REMOTE_USERNAME@$SSH_REMOTE_IP:$PATH_TO_THE_REMOTE_DIRECTORY

LOCAL_DIRECTORY=${1}
REMOTE_DESTINATION=${2}
PARALLELS=${3:-4}

ls $LOCAL_DIRECTORY | xargs -n1 -P$PARALLELS -I% scp -r $LOCAL_DIRECTORY $REMOTE_DESTINATION
